version: '3.8'

services:
  db:
    image: mongo:4.2
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./data/dump:/dump

  app:
    image: 192.168.100.47:8083/nodemongoapp:IMAGE_TAG  # Placeholder pour le tag dynamique
    container_name: back
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  mongo-data: